name: Wheels

# Publish when a (published) GitHub Release is created.
on:
  push:
    branches:
      - master
      - 'releases/**'
      - gha-macos-windows-ci
    tags:
      - v*
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-18.04' ]

    steps:

      - name: Acquire sources
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Apply caching
        id: cache
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if requirements*.txt has not changed
          CACHE_NUMBER: 4
        with:
          path: |
            ~/.cache
            ~/conda_pkgs_dir
            #/usr/local/Cellar
          key:
            ${{ runner.os }}-pythonpkg-${{ env.CACHE_NUMBER }}-${{ hashFiles('requirements.txt', 'requirements-dev.txt', 'requirements-docs.txt') }}

      - name: Install Miniconda
        if: contains(matrix.os, 'windows')

        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: defaults,conda-forge
          use-only-tar-bz2: true

      - uses: docker/setup-qemu-action@v1
        if:  ${{matrix.arch}} == 'aarch64'
        name: Set up QEMU

      - name: Install cibuildwheel
        run: |
          pip install cibuildwheel==1.8.0

      # General note:
      # We wanted to handle this all within a single `cibuildwheel` action,
      # but things are a bit involved, so we split that between Linux/macOS
      # 32-bit vs. 64-bit and Windows.


      # The workhorse for Linux and macOS 64-bit.
      #
      # This uses the vanilla way of `cibuildwheel`. For building on Linux,
      # it uses the fine `manylinux` images. Because neither `manylinux1`
      # nor `manylinux2010` apparently ship `blosc-devel` packages, we
      # switch to `manylinux2014`. For building on macOS, it uses Homebrew.

      - name: Install prerequisites for macOS
        if: contains(matrix.os, 'macos') # && steps.cache.outputs.cache-hit != 'true'
        env:
          # Best compatibility, even with older releases of macOS.
          MACOSX_DEPLOYMENT_TARGET: "10.9"
        run: |
          brew install --build-from-source --no-binaries --force szip
          brew reinstall --build-from-source --no-binaries --force c-blosc bzip2 hdf5 lz4 lzo snappy zstd zlib
          brew link --overwrite --force bzip2 zlib

      - name: Build wheels for Linux or macOS (64-bit)
        if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
        run: cibuildwheel --output-dir wheelhouse
        env:

          CIBW_BUILD: "cp36-manylinux_x86_64 cp37-manylinux_x86_64 cp38-manylinux_x86_64 cp39-manylinux_x86_64 cp36-macosx_x86_64 cp37-macosx_x86_64 cp38-macosx_x86_64 cp39-macosx_x86_64"
          CIBW_ENVIRONMENT: "PYTABLES_NO_EMBEDDED_LIBS=true DISABLE_AVX2=true"
          CIBW_BEFORE_BUILD: "pip install --requirement=requirements.txt --requirement=requirements-dev.txt"
          CIBW_BUILD_VERBOSITY: 3

          # Linux specific configuration.
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BEFORE_ALL_LINUX: "yum install -y blosc-devel bzip2-devel hdf5-devel lz4-devel lzo-devel snappy-devel libzstd-devel zlib-devel"

          # macOS specific configuration.
          # Best compatibility, even with older releases of macOS.
          MACOSX_DEPLOYMENT_TARGET: "10.9"
          CIBW_ENVIRONMENT_MACOS: BZIP2_DIR=/usr/local/opt/bzip2 LDFLAGS+="-L/usr/local/opt/bzip2/lib -L/usr/local/opt/zlib/lib" CPPFLAGS+="-I/usr/local/opt/bzip2/include -I/usr/local/opt/zlib/include" PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"


      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:

      - name: Acquire sources
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Debian packages
        if: contains(${{ matrix.os }}, 'ubuntu')
        run: |
          sudo apt install libblosc-dev libbz2-dev libhdf5-dev liblz4-dev liblzo2-dev libsnappy-dev libzstd-dev zlib1g-dev
          sudo apt install latexmk texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra texlive-plain-generic

      - name: Install dependencies
        run: |
          pip install --upgrade setuptools pip wheel
          pip install --requirement=requirements.txt --requirement=requirements-dev.txt
          pip install --requirement=requirements-docs.txt

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    # upload to PyPI on every tag starting with 'v'
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    # alternatively, to publish when a GitHub Release is created, use the following rule:
    # if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
          skip_existing: true

          # Use for testing.
          #repository_url: https://test.pypi.org/legacy/
